version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: vm-mania-2026
    restart: always
    ports:
      - '3000:3000'
    volumes:
      # Mounts local ./data to /app/data inside the container to persist the SQLite DB
      - ./data:/app/data
    env_file:
      - .env
